$pdf_mode = 1;
$out_dir = 'build';
$aux_dir = 'build';

$pdflatex = 'pdflatex -interaction=nonstopmode -halt-on-error -file-line-error %O %S';
$bibtex_use = 2;

$cleanup_includes_cusdep_generated = 1;
@generated_exts = (
  @generated_exts,
  'bbl',
  'bcf',
  'blg',
  'lof',
  'lot',
  'out',
  'run.xml',
  'synctex.gz',
  'toc'
);
